[package]
name = "malware-detect"
version = "0.1.0"
authors = ["Zsolt Varga <hello@hisorange.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0.7.15"
chrono = "0.4.19"
clap = "2.33.3"
csv = "1.1.4"
md5 = "0.7.0"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
took = "0.1.2"
walkdir = "2.3.1"